jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - run: aws --version
      - run: npm --version
      - run: aws sts get-caller-identity

