version: 2.1

jobs:
  verify_aws_access:
    resource_class: small
    docker: 
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - run: aws sts get-caller-identity

  build:
    resource_class: small
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - run: aws --version
      - run: npm --version
      - run: env
workflows:
  build:
    jobs:      
      - verify_aws_access:
          context: test
      - build:
          context: test
          requires:
            - verify_aws_access


